export interface EmojiCombination {
  id: string;
  emoji: string[];
  tags: string[];
  popularity: number;
}

export interface TopicEmojiData {
  id: string;
  name: string;
  slug: string;
  icon: string;
  description: string;
  primaryEmojis: string[];
  combinations: EmojiCombination[];
  relatedTopics: string[];
}

export const topicEmojiData: TopicEmojiData[] = [
  {
    id: "berry",
    name: "Berry",
    slug: "berry",
    icon: "🫐",
    description:
      "Explore beautiful berry emoji combinations and aesthetic text art",
    primaryEmojis: ["🫐", "🍓", "🍒", "🍇"],
    relatedTopics: ["star", "moon"],
    combinations: [
      {
        id: "berry-1",
        emoji: ["🫐", "🍇", "🍓", "🍒"],
        tags: ["berries", "mix", "fruit"],
        popularity: 95,
      },
      {
        id: "berry-2",
        emoji: ["˙", "✩", "°", "˖", "🫐", "⋆", "｡", "˚", "꩜"],
        tags: ["aesthetic", "decorative", "sparkles"],
        popularity: 88,
      },
      {
        id: "berry-3",
        emoji: ["⋆", "｡", "‧", "˚", "ʚ", "🍓", "ɞ", "˚", "‧", "｡", "⋆"],
        tags: ["aesthetic", "hearts", "decorative"],
        popularity: 92,
      },
      {
        id: "berry-4",
        emoji: ["๋", "࣭", "⭑", "🍒", "🍓", "๋", "࣭", "⭑"],
        tags: ["aesthetic", "stars", "decorative"],
        popularity: 85,
      },
      {
        id: "berry-5",
        emoji: ["⋆", "˚", "🫐", "˙", "✩", "°", "˖"],
        tags: ["stars", "sparkles", "blueberry"],
        popularity: 82,
      },
      {
        id: "berry-6",
        emoji: ["♡", "。", "✿", "🍓", "。", "✿", "♡"],
        tags: ["flowers", "hearts", "nature"],
        popularity: 79,
      },
      {
        id: "berry-7",
        emoji: ["🍇", "⋆", "。", "✦", "。", "⋆", "🍇"],
        tags: ["grapes", "stars", "decorative"],
        popularity: 76,
      },
      {
        id: "berry-8",
        emoji: ["🦋", "🍒", "🌸", "🦋"],
        tags: ["butterfly", "cherry", "spring"],
        popularity: 74,
      },
      {
        id: "berry-9",
        emoji: ["🫐", "☁️", "☁️", "🫐"],
        tags: ["blueberry", "clouds", "sky"],
        popularity: 71,
      },
      {
        id: "berry-10",
        emoji: ["🍓", "⊹", "✿", "⊹", "🍓"],
        tags: ["strawberry", "flowers", "nature"],
        popularity: 69,
      },
      {
        id: "berry-11",
        emoji: ["🍒", "・", "♡", "・", "🍒"],
        tags: ["cherry", "hearts", "romantic"],
        popularity: 67,
      },
      {
        id: "berry-12",
        emoji: ["⋆", "🍇", "˚", ",", "🍇", "⋆"],
        tags: ["grapes", "stars", "sparkles"],
        popularity: 65,
      },
      {
        id: "berry-13",
        emoji: ["💜", "🫐", "💜"],
        tags: ["purple", "blueberry", "color"],
        popularity: 63,
      },
      {
        id: "berry-14",
        emoji: ["🍓", "₊", "˚", "˙", "🍓"],
        tags: ["strawberry", "sparkles", "cute"],
        popularity: 61,
      },
      {
        id: "berry-15",
        emoji: ["🍒", "ˎ", "ˏ", "♡", "ˎ", "ˏ"],
        tags: ["cherry", "hearts", "kaomoji"],
        popularity: 59,
      },
      {
        id: "berry-16",
        emoji: ["🫐", "*", "ೃ", "🍇", "*"],
        tags: ["berries", "stars", "decorative"],
        popularity: 57,
      },
      {
        id: "berry-17",
        emoji: ["。", "🍓", "✦", "🍓", "。"],
        tags: ["strawberry", "sparkles", "dots"],
        popularity: 55,
      },
      {
        id: "berry-18",
        emoji: ["🍒", "*:･", "ﾟ", "*:･", "🍒"],
        tags: ["cherry", "sparkles", "aesthetic"],
        popularity: 53,
      },
      {
        id: "berry-19",
        emoji: ["⋆", "˚", "🫐", "˙", "✩", "⋆"],
        tags: ["blueberry", "stars", "sparkles"],
        popularity: 51,
      },
      {
        id: "berry-20",
        emoji: ["⊹", "🍇", "⊹", "✿", "⊹"],
        tags: ["grapes", "flowers", "decorative"],
        popularity: 49,
      },
    ],
  },
  {
    id: "heart",
    name: "Heart",
    slug: "heart",
    icon: "❤️",
    description: "Beautiful heart emoji combinations for love and affection",
    primaryEmojis: [
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❣️",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
    ],
    relatedTopics: ["sparkle", "flower"],
    combinations: [
      {
        id: "heart-1",
        emoji: ["💖", "💗", "💓", "💘", "💝"],
        tags: ["love", "hearts", "romantic"],
        popularity: 98,
      },
      {
        id: "heart-2",
        emoji: ["˙", "♡", "˙", "✩", "°", "˖"],
        tags: ["aesthetic", "hearts", "sparkles"],
        popularity: 95,
      },
      {
        id: "heart-3",
        emoji: ["♡", "⋅", "✧", "♡", "⋅", "✧"],
        tags: ["hearts", "stars", "decorative"],
        popularity: 92,
      },
      {
        id: "heart-4",
        emoji: ["💕", "🌸", "💕", "🌸"],
        tags: ["love", "flowers", "romantic"],
        popularity: 89,
      },
      {
        id: "heart-5",
        emoji: ["⋆", "｡", "‧", "˚", "♡", "‧", "｡", "⋆"],
        tags: ["hearts", "stars", "aesthetic"],
        popularity: 87,
      },
      {
        id: "heart-6",
        emoji: ["💓", "☁️", "☁️", "💓"],
        tags: ["hearts", "clouds", "romantic"],
        popularity: 84,
      },
      {
        id: "heart-7",
        emoji: ["🫧", "♡", "🫧", "♡", "🫧"],
        tags: ["bubbles", "hearts", "cute"],
        popularity: 81,
      },
      {
        id: "heart-8",
        emoji: ["🦋", "♡", "💕", "♡", "🦋"],
        tags: ["butterfly", "love", "hearts"],
        popularity: 79,
      },
      {
        id: "heart-9",
        emoji: ["💗", "*", "⋆", "。", "⋆", "*", "💗"],
        tags: ["hearts", "stars", "sparkles"],
        popularity: 77,
      },
      {
        id: "heart-10",
        emoji: ["💖", "。", "✿", "。", "💖"],
        tags: ["hearts", "flowers", "love"],
        popularity: 75,
      },
    ],
  },
  {
    id: "flower",
    name: "Flower",
    slug: "flower",
    icon: "🌸",
    description: "Beautiful flower emoji combinations and nature art",
    primaryEmojis: [
      "🌸",
      "🌺",
      "🌻",
      "🌹",
      "🌷",
      "🌼",
      "💐",
      "🪻",
      "🪷",
      "🌱",
      "🌿",
      "☘️",
    ],
    relatedTopics: ["butterfly", "spring"],
    combinations: [
      {
        id: "flower-1",
        emoji: ["🌸", "🌺", "🌻", "🌹", "🌷"],
        tags: ["flowers", "spring", "nature"],
        popularity: 94,
      },
      {
        id: "flower-2",
        emoji: ["⋆", "｡", "˚", "🌸", "˚", "｡", "⋆"],
        tags: ["cherry blossom", "aesthetic", "stars"],
        popularity: 91,
      },
      {
        id: "flower-3",
        emoji: ["🌷", "⊹", "✿", "⊹", "🌷"],
        tags: ["tulip", "flowers", "nature"],
        popularity: 88,
      },
      {
        id: "flower-4",
        emoji: ["🌻", "。", "✦", "。", "🌻"],
        tags: ["sunflower", "sun", "summer"],
        popularity: 86,
      },
      {
        id: "flower-5",
        emoji: ["💐", "♡", "🌸", "♡", "💐"],
        tags: ["bouquet", "hearts", "gift"],
        popularity: 83,
      },
      {
        id: "flower-6",
        emoji: ["🌹", "⋆", "。", "✦", "。", "⋆", "🌹"],
        tags: ["rose", "love", "romantic"],
        popularity: 81,
      },
      {
        id: "flower-7",
        emoji: ["🌿", "🌱", "🌸", "🌱", "🌿"],
        tags: ["leaves", "growth", "nature"],
        popularity: 78,
      },
      {
        id: "flower-8",
        emoji: ["🦋", "🌸", "🌸", "🦋"],
        tags: ["butterfly", "cherry blossom", "spring"],
        popularity: 76,
      },
      {
        id: "flower-9",
        emoji: ["🪻", "。", "✿", "。", "🪻"],
        tags: ["lavender", "purple", "calm"],
        popularity: 73,
      },
      {
        id: "flower-10",
        emoji: ["🌼", "*", "⋆", "。", "⋆", "*", "🌼"],
        tags: ["blossom", "stars", "spring"],
        popularity: 71,
      },
    ],
  },
  {
    id: "butterfly",
    name: "Butterfly",
    slug: "butterfly",
    icon: "🦋",
    description: "Elegant butterfly emoji combinations and magical nature art",
    primaryEmojis: ["🦋", "🐛", "🐌", "🐝", "🐞", "🪲", "🪳", "🦗", "🕷️", "🕸️"],
    relatedTopics: ["flower", "rainbow"],
    combinations: [
      {
        id: "butterfly-1",
        emoji: ["🦋", "🌸", "🌸", "🦋"],
        tags: ["butterfly", "flowers", "spring"],
        popularity: 96,
      },
      {
        id: "butterfly-2",
        emoji: ["⋆", "｡", "˚", "🦋", "˚", "｡", "⋆"],
        tags: ["aesthetic", "stars", "elegant"],
        popularity: 93,
      },
      {
        id: "butterfly-3",
        emoji: ["🦋", "。", "✿", "。", "🦋"],
        tags: ["butterfly", "flowers", "nature"],
        popularity: 90,
      },
      {
        id: "butterfly-4",
        emoji: ["🦋", "⊹", "♡", "⊹", "🦋"],
        tags: ["butterfly", "hearts", "cute"],
        popularity: 87,
      },
      {
        id: "butterfly-5",
        emoji: ["🌸", "🦋", "💨", "🦋", "🌸"],
        tags: ["cherry blossom", "wind", "magic"],
        popularity: 84,
      },
      {
        id: "butterfly-6",
        emoji: ["🦋", "⋆", "。", "✦", "。", "⋆", "🦋"],
        tags: ["butterfly", "stars", "sparkles"],
        popularity: 82,
      },
      {
        id: "butterfly-7",
        emoji: ["🌈", "🦋", "🌈"],
        tags: ["rainbow", "magic", "colorful"],
        popularity: 79,
      },
      {
        id: "butterfly-8",
        emoji: ["💐", "🦋", "🌸", "🦋", "💐"],
        tags: ["bouquet", "flowers", "spring"],
        popularity: 76,
      },
      {
        id: "butterfly-9",
        emoji: ["🫧", "🦋", "🫧", "🦋"],
        tags: ["bubbles", "butterfly", "cute"],
        popularity: 73,
      },
      {
        id: "butterfly-10",
        emoji: ["✨", "🦋", "✨", "🦋", "✨"],
        tags: ["sparkles", "magic", "elegant"],
        popularity: 71,
      },
    ],
  },
  {
    id: "star",
    name: "Star",
    slug: "star",
    icon: "⭐",
    description: "Sparkling star emoji combinations and celestial art",
    primaryEmojis: ["⭐", "🌟", "✨", "💫", "☀️", "🌙", "🪐", "💠", "🔯"],
    relatedTopics: ["sparkle", "moon"],
    combinations: [
      {
        id: "star-1",
        emoji: ["⭐", "🌟", "✨", "💫"],
        tags: ["stars", "sparkles", "magic"],
        popularity: 97,
      },
      {
        id: "star-2",
        emoji: ["˙", "✩", "°", "˖", "⭐", "⋆", "｡", "˚"],
        tags: ["aesthetic", "decorative", "sparkles"],
        popularity: 94,
      },
      {
        id: "star-3",
        emoji: ["⋆", "｡", "‧", "˚", "🌙", "‧", "｡", "⋆"],
        tags: ["moon", "stars", "night"],
        popularity: 92,
      },
      {
        id: "star-4",
        emoji: ["✨", "⋆", "。", "✦", "。", "⋆", "✨"],
        tags: ["sparkles", "stars", "magic"],
        popularity: 89,
      },
      {
        id: "star-5",
        emoji: ["🌙", "⭐", "🌙", "⭐"],
        tags: ["moon", "stars", "night"],
        popularity: 87,
      },
      {
        id: "star-6",
        emoji: ["⭐", "☁️", "☁️", "⭐"],
        tags: ["stars", "clouds", "sky"],
        popularity: 84,
      },
      {
        id: "star-7",
        emoji: ["💫", "⋆", "。", "✦", "。", "⋆", "💫"],
        tags: ["sparkles", "stars", "magic"],
        popularity: 82,
      },
      {
        id: "star-8",
        emoji: ["🌟", "。", "✿", "。", "🌟"],
        tags: ["glowing star", "flowers", "sparkles"],
        popularity: 79,
      },
      {
        id: "star-9",
        emoji: ["🦋", "⭐", "🦋", "⭐"],
        tags: ["butterfly", "stars", "magic"],
        popularity: 76,
      },
      {
        id: "star-10",
        emoji: ["💖", "⭐", "💖", "⭐"],
        tags: ["hearts", "stars", "love"],
        popularity: 74,
      },
    ],
  },
  {
    id: "sparkle",
    name: "Sparkle",
    slug: "sparkle",
    icon: "✨",
    description: "Shimmering sparkle emoji combinations for aesthetic vibes",
    primaryEmojis: ["✨", "💫", "⭐", "🌟", "💥", "💯", "❣️", "💥"],
    relatedTopics: ["star", "butterfly"],
    combinations: [
      {
        id: "sparkle-1",
        emoji: ["✨", "⋆", "。", "✦", "。", "⋆", "✨"],
        tags: ["sparkles", "stars", "magic"],
        popularity: 98,
      },
      {
        id: "sparkle-2",
        emoji: ["˙", "✩", "°", "˖", "✨", "⋆", "｡", "˚", "꩜"],
        tags: ["aesthetic", "decorative", "sparkles"],
        popularity: 95,
      },
      {
        id: "sparkle-3",
        emoji: ["✨", "˙", "♡", "˙", "✨"],
        tags: ["sparkles", "hearts", "cute"],
        popularity: 92,
      },
      {
        id: "sparkle-4",
        emoji: ["💫", "⋆", "。", "✦", "。", "⋆", "💫"],
        tags: ["sparkles", "stars", "magic"],
        popularity: 90,
      },
      {
        id: "sparkle-5",
        emoji: ["✨", "。", "✿", "。", "✨"],
        tags: ["sparkles", "flowers", "nature"],
        popularity: 87,
      },
      {
        id: "sparkle-6",
        emoji: ["⋆", "˚", "✩", "˙", "✨", "˙", "✩", "˚", "⋆"],
        tags: ["stars", "sparkles", "aesthetic"],
        popularity: 85,
      },
      {
        id: "sparkle-7",
        emoji: ["✨", "🦋", "✨", "🦋"],
        tags: ["sparkles", "butterfly", "magic"],
        popularity: 82,
      },
      {
        id: "sparkle-8",
        emoji: ["✨", "🌸", "✨", "🌸"],
        tags: ["sparkles", "cherry blossom", "spring"],
        popularity: 80,
      },
      {
        id: "sparkle-9",
        emoji: ["💥", "✨", "💥", "✨"],
        tags: ["explosion", "sparkles", "impact"],
        popularity: 77,
      },
      {
        id: "sparkle-10",
        emoji: ["✨", "⋆", "˚", ",", "˚", "⋆", "✨"],
        tags: ["sparkles", "stars", "decorative"],
        popularity: 75,
      },
    ],
  },
  {
    id: "moon",
    name: "Moon",
    slug: "moon",
    icon: "🌙",
    description: "Beautiful moon emoji combinations and night sky art",
    primaryEmojis: [
      "🌙",
      "🌝",
      "🌛",
      "🌜",
      "🌚",
      "🌕",
      "🌖",
      "🌗",
      "🌘",
      "🌑",
      "🌒",
      "🌓",
      "☀️",
      "⭐",
      "💫",
    ],
    relatedTopics: ["star", "cloud"],
    combinations: [
      {
        id: "moon-1",
        emoji: ["🌙", "⭐", "🌙", "⭐"],
        tags: ["moon", "stars", "night"],
        popularity: 96,
      },
      {
        id: "moon-2",
        emoji: ["⋆", "｡", "‧", "˚", "🌙", "‧", "｡", "⋆"],
        tags: ["moon", "stars", "night"],
        popularity: 93,
      },
      {
        id: "moon-3",
        emoji: ["🌝", "✨", "🌝"],
        tags: ["full moon", "bright", "night"],
        popularity: 90,
      },
      {
        id: "moon-4",
        emoji: ["🌙", "☁️", "☁️", "🌙"],
        tags: ["moon", "clouds", "night"],
        popularity: 88,
      },
      {
        id: "moon-5",
        emoji: ["🌕", "⋆", "。", "✦", "。", "⋆", "🌕"],
        tags: ["full moon", "stars", "magic"],
        popularity: 85,
      },
      {
        id: "moon-6",
        emoji: ["🌙", "🌸", "🌸", "🌙"],
        tags: ["moon", "cherry blossom", "night"],
        popularity: 82,
      },
      {
        id: "moon-7",
        emoji: ["🌛", "💫", "⋆", "✨"],
        tags: ["crescent moon", "sparkles", "magic"],
        popularity: 80,
      },
      {
        id: "moon-8",
        emoji: ["✨", "🌜", "✨", "🌜"],
        tags: ["last quarter moon", "sparkles", "night"],
        popularity: 77,
      },
      {
        id: "moon-9",
        emoji: ["🌚", "⋆", "。", "✦", "。", "⋆", "🌚"],
        tags: ["new moon", "stars", "dark"],
        popularity: 74,
      },
      {
        id: "moon-10",
        emoji: ["🦋", "🌙", "🦋", "🌙"],
        tags: ["butterfly", "moon", "magic"],
        popularity: 72,
      },
    ],
  },
  {
    id: "cloud",
    name: "Cloud",
    slug: "cloud",
    icon: "☁️",
    description: "Fluffy cloud emoji combinations and sky aesthetics",
    primaryEmojis: ["☁️", "🌥️", "🌦️", "🌧️", "⛅", "🌤️", "🌩️", "🌪️", "🌫️"],
    relatedTopics: ["rainbow", "moon"],
    combinations: [
      {
        id: "cloud-1",
        emoji: ["☁️", "☁️", "☁️"],
        tags: ["clouds", "sky", "fluffy"],
        popularity: 94,
      },
      {
        id: "cloud-2",
        emoji: ["☁️", "⭐", "☁️", "⭐"],
        tags: ["clouds", "stars", "sky"],
        popularity: 91,
      },
      {
        id: "cloud-3",
        emoji: ["☁️", "🌸", "☁️", "🌸"],
        tags: ["clouds", "cherry blossom", "spring"],
        popularity: 88,
      },
      {
        id: "cloud-4",
        emoji: ["☁️", "🦋", "☁️", "🦋"],
        tags: ["clouds", "butterfly", "nature"],
        popularity: 86,
      },
      {
        id: "cloud-5",
        emoji: ["🌈", "☁️", "🌈"],
        tags: ["rainbow", "clouds", "colorful"],
        popularity: 83,
      },
      {
        id: "cloud-6",
        emoji: ["☁️", "⋆", "。", "✦", "。", "⋆", "☁️"],
        tags: ["clouds", "stars", "sparkles"],
        popularity: 81,
      },
      {
        id: "cloud-7",
        emoji: ["☁️", "🌙", "☁️", "🌙"],
        tags: ["clouds", "moon", "night"],
        popularity: 78,
      },
      {
        id: "cloud-8",
        emoji: ["☁️", "💖", "☁️", "💖"],
        tags: ["clouds", "hearts", "love"],
        popularity: 76,
      },
      {
        id: "cloud-9",
        emoji: ["☁️", "🍓", "☁️", "🍓"],
        tags: ["clouds", "strawberry", "cute"],
        popularity: 73,
      },
      {
        id: "cloud-10",
        emoji: ["☁️", "⊹", "✿", "⊹", "☁️"],
        tags: ["clouds", "flowers", "nature"],
        popularity: 71,
      },
    ],
  },
  {
    id: "rainbow",
    name: "Rainbow",
    slug: "rainbow",
    icon: "🌈",
    description: "Colorful rainbow emoji combinations and vibrant art",
    primaryEmojis: ["🌈", "💜", "💙", "💚", "💛", "🧡", "❤️", "🖤", "🤍", "🤎"],
    relatedTopics: ["cloud", "butterfly"],
    combinations: [
      {
        id: "rainbow-1",
        emoji: ["🌈", "💜", "💙", "💚", "💛", "🧡", "❤️"],
        tags: ["rainbow", "colors", "pride"],
        popularity: 98,
      },
      {
        id: "rainbow-2",
        emoji: ["🌈", "✨", "🌈", "✨"],
        tags: ["rainbow", "sparkles", "magic"],
        popularity: 95,
      },
      {
        id: "rainbow-3",
        emoji: ["🦋", "🌈", "🦋"],
        tags: ["butterfly", "rainbow", "colorful"],
        popularity: 92,
      },
      {
        id: "rainbow-4",
        emoji: ["🌈", "☁️", "☁️", "🌈"],
        tags: ["rainbow", "clouds", "sky"],
        popularity: 89,
      },
      {
        id: "rainbow-5",
        emoji: ["🌈", "⋆", "。", "✦", "。", "⋆", "🌈"],
        tags: ["rainbow", "stars", "magic"],
        popularity: 87,
      },
      {
        id: "rainbow-6",
        emoji: ["🌸", "🌈", "🌸"],
        tags: ["cherry blossom", "rainbow", "spring"],
        popularity: 84,
      },
      {
        id: "rainbow-7",
        emoji: ["🌈", "💕", "🌈", "💕"],
        tags: ["rainbow", "hearts", "love"],
        popularity: 82,
      },
      {
        id: "rainbow-8",
        emoji: ["🌈", "🫧", "🌈", "🫧"],
        tags: ["rainbow", "bubbles", "colorful"],
        popularity: 79,
      },
      {
        id: "rainbow-9",
        emoji: ["🌈", "☀️", "🌈", "☀️"],
        tags: ["rainbow", "sun", "bright"],
        popularity: 76,
      },
      {
        id: "rainbow-10",
        emoji: ["🌈", "🦋", "🌈", "🦋"],
        tags: ["rainbow", "butterfly", "magic"],
        popularity: 74,
      },
    ],
  },
  {
    id: "music",
    name: "Music",
    slug: "music",
    icon: "🎵",
    description: "Musical emoji combinations and melody art",
    primaryEmojis: [
      "🎵",
      "🎶",
      "🎼",
      "🎤",
      "🎧",
      "🎸",
      "🎹",
      "🎺",
      "🎻",
      "🥁",
      "🪘",
    ],
    relatedTopics: ["cat", "dog"],
    combinations: [
      {
        id: "music-1",
        emoji: ["🎵", "🎶", "🎼"],
        tags: ["music", "notes", "melody"],
        popularity: 96,
      },
      {
        id: "music-2",
        emoji: ["⋆", "｡", "‧", "˚", "🎵", "‧", "｡", "⋆"],
        tags: ["music", "stars", "aesthetic"],
        popularity: 93,
      },
      {
        id: "music-3",
        emoji: ["🎤", "🎧", "🎵", "🎶"],
        tags: ["singing", "music", "entertainment"],
        popularity: 90,
      },
      {
        id: "music-4",
        emoji: ["🎸", "⋆", "。", "✦", "。", "⋆", "🎸"],
        tags: ["guitar", "stars", "rock"],
        popularity: 87,
      },
      {
        id: "music-5",
        emoji: ["🎹", "☁️", "☁️", "🎹"],
        tags: ["piano", "clouds", "melody"],
        popularity: 84,
      },
      {
        id: "music-6",
        emoji: ["🎶", "♡", "🎶", "♡"],
        tags: ["music notes", "hearts", "love"],
        popularity: 82,
      },
      {
        id: "music-7",
        emoji: ["🎵", "✨", "🎵", "✨"],
        tags: ["music", "sparkles", "magic"],
        popularity: 79,
      },
      {
        id: "music-8",
        emoji: ["🎻", "🌙", "🎻", "🌙"],
        tags: ["violin", "moon", "elegant"],
        popularity: 76,
      },
      {
        id: "music-9",
        emoji: ["🎺", "🦋", "🎺", "🦋"],
        tags: ["trumpet", "butterfly", "colorful"],
        popularity: 73,
      },
      {
        id: "music-10",
        emoji: ["🎵", "⊹", "✿", "⊹", "🎵"],
        tags: ["music", "flowers", "nature"],
        popularity: 71,
      },
    ],
  },
  {
    id: "cat",
    name: "Cat",
    slug: "cat",
    icon: "🐱",
    description: "Cute cat emoji combinations and feline fun",
    primaryEmojis: [
      "🐱",
      "🐈",
      "🐈‍⬛",
      "🦁",
      "🐯",
      "🐆",
      "🐅",
      "🐆",
      "🐆",
      "🐈",
    ],
    relatedTopics: ["dog", "music"],
    combinations: [
      {
        id: "cat-1",
        emoji: ["🐱", "🐈", "🐈‍⬛"],
        tags: ["cats", "kittens", "cute"],
        popularity: 97,
      },
      {
        id: "cat-2",
        emoji: ["⋆", "｡", "‧", "˚", "🐱", "‧", "｡", "⋆"],
        tags: ["cat", "stars", "cute"],
        popularity: 94,
      },
      {
        id: "cat-3",
        emoji: ["🐱", "⊹", "♡", "⊹", "🐱"],
        tags: ["cat", "hearts", "love"],
        popularity: 91,
      },
      {
        id: "cat-4",
        emoji: ["🐈‍⬛", "✨", "🐈‍⬛", "✨"],
        tags: ["black cat", "sparkles", "magic"],
        popularity: 88,
      },
      {
        id: "cat-5",
        emoji: ["🐱", "。", "✿", "。", "🐱"],
        tags: ["cat", "flowers", "nature"],
        popularity: 86,
      },
      {
        id: "cat-6",
        emoji: ["🦁", "⋆", "。", "✦", "。", "⋆", "🦁"],
        tags: ["lion", "king", "stars"],
        popularity: 83,
      },
      {
        id: "cat-7",
        emoji: ["🐯", "☁️", "☁️", "🐯"],
        tags: ["tiger", "clouds", "nature"],
        popularity: 80,
      },
      {
        id: "cat-8",
        emoji: ["🐱", "🐟", "🐱", "🐟"],
        tags: ["cat", "fish", "food"],
        popularity: 77,
      },
      {
        id: "cat-9",
        emoji: ["🐈", "🌸", "🐈", "🌸"],
        tags: ["cat", "cherry blossom", "spring"],
        popularity: 75,
      },
      {
        id: "cat-10",
        emoji: ["🐱", "🧶", "🐱", "🧶"],
        tags: ["cat", "yarn", "playful"],
        popularity: 72,
      },
    ],
  },
  {
    id: "dog",
    name: "Dog",
    slug: "dog",
    icon: "🐶",
    description: "Adorable dog emoji combinations and puppy love",
    primaryEmojis: [
      "🐶",
      "🐕",
      "🐩",
      "🐕‍🦺",
      "🐺",
      "🦊",
      "🦝",
      "🦝",
      "🦊",
      "🐕",
    ],
    relatedTopics: ["cat", "music"],
    combinations: [
      {
        id: "dog-1",
        emoji: ["🐶", "🐕", "🐩"],
        tags: ["dogs", "puppy", "cute"],
        popularity: 96,
      },
      {
        id: "dog-2",
        emoji: ["⋆", "｡", "‧", "˚", "🐶", "‧", "｡", "⋆"],
        tags: ["dog", "stars", "cute"],
        popularity: 93,
      },
      {
        id: "dog-3",
        emoji: ["🐶", "⊹", "♡", "⊹", "🐶"],
        tags: ["dog", "hearts", "love"],
        popularity: 90,
      },
      {
        id: "dog-4",
        emoji: ["🦊", "✨", "🦊", "✨"],
        tags: ["fox", "sparkles", "magic"],
        popularity: 87,
      },
      {
        id: "dog-5",
        emoji: ["🐕", "🦴", "🐕", "🦴"],
        tags: ["dog", "bone", "playful"],
        popularity: 85,
      },
      {
        id: "dog-6",
        emoji: ["🐺", "🌙", "🐺", "🌙"],
        tags: ["wolf", "moon", "night"],
        popularity: 82,
      },
      {
        id: "dog-7",
        emoji: ["🐶", "☁️", "☁️", "🐶"],
        tags: ["dog", "clouds", "sky"],
        popularity: 79,
      },
      {
        id: "dog-8",
        emoji: ["🐕", "🎾", "🐕", "🎾"],
        tags: ["dog", "tennis", "playful"],
        popularity: 76,
      },
      {
        id: "dog-9",
        emoji: ["🐶", "🌸", "🐶", "🌸"],
        tags: ["dog", "cherry blossom", "spring"],
        popularity: 74,
      },
      {
        id: "dog-10",
        emoji: ["🐩", "⋆", "。", "✦", "。", "⋆", "🐩"],
        tags: ["poodle", "stars", "elegant"],
        popularity: 71,
      },
    ],
  },
];

export function getTopicBySlug(slug: string): TopicEmojiData | undefined {
  return topicEmojiData.find((topic) => topic.slug === slug);
}

export function isValidTopic(slug: string): boolean {
  return topicEmojiData.some((topic) => topic.slug === slug);
}

export function getAllTopics(): TopicEmojiData[] {
  return topicEmojiData;
}

export function getPopularTopics(limit: number = 6): TopicEmojiData[] {
  return [...topicEmojiData]
    .sort((a, b) => {
      const aMaxPop = Math.max(...a.combinations.map((c) => c.popularity));
      const bMaxPop = Math.max(...b.combinations.map((c) => c.popularity));
      return bMaxPop - aMaxPop;
    })
    .slice(0, limit);
}
